# For more information: https://laravel.com/docs/sail
version: '3'
services:
  backend:
    #    image: us-east1-docker.pkg.dev/utilis-217318/utilis-spa/backend:staging
    image: app-test
    container_name: app
    restart: unless-stopped
    environment:
      APP_NAME: "${APP_NAME}"
      APP_ENV: "${APP_ENV}"
      APP_KEY: "${APP_KEY}"
      APP_DEBUG: "${APP_DEBUG}"
      APP_URL: "${APP_URL}"
      LOG_CHANNEL: "${LOG_CHANNEL}"
      LOG_LEVEL: "${LOG_LEVEL}"
      DB_HOST: "${DB_HOST}"
      DB_PORT: "${DB_PORT}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_USERNAME: "${DB_USERNAME}"
      DB_PASSWORD: "${DB_PASSWORD}"
      REDIS_HOST: "${REDIS_HOST}"
      MAIL_FROM_NAME: "${APP_NAME}"
      SESSION_DOMAIN: "${SESSION_DOMAIN}"
      SANCTUM_STATEFUL_DOMAINS: "${SANCTUM_STATEFUL_DOMAINS}"
    entrypoint: /entrypoint-local.sh
    volumes:
      - type: bind
        source: ./scripts/entrypoint-local.sh
        target: /entrypoint-local.sh
    #      - ${PWD}/README.md:/README.md
    networks:
      - app-net

  nginx:
    image: nginx:1.17-alpine
    container_name: app-net-nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./docker/conf/nginx:/etc/nginx/conf.d
    networks:
      - app-net

  pgsql:
    image: postgis/postgis:14-master
    ports:
      - '${FORWARD_DB_PORT:-5432}:5432'
    environment:
      PGPASSWORD: '${DB_PASSWORD:-secret}'
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_USER: '${DB_USERNAME}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
    volumes:
      - 'database:/var/lib/postgresql/data'
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}" ]

  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'redis:/data'
    networks:
      - app-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]

networks:
  app-net:
    driver: bridge
volumes:
  database:
    driver: local
  redis:
    driver: local
